version: '1.0'
project:
  name: TKXR Project
  created: 2026-02-20T00:07:33.385Z
  updated: 2026-02-20T00:25:19.460Z
tickets:
  - id: tas-0oTc10Cq
    type: task
    title: Put "All Tickets" at the end, add "All Open"
    status: done
    createdAt: 2026-02-19T20:23:19.964Z
    updatedAt: 2026-02-19T20:53:46.619Z
    description: >-
      Currently, All Tickets is the first option (from the left) and selected by default. Put it at the end, after done.
      Default to showing "All Open" a new category comprising all tasks and bugs not done.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 1
  - id: tas-14eWaSjK
    type: task
    title: Add Kanban View
    status: done
    createdAt: 2026-02-19T21:06:12.696Z
    updatedAt: 2026-02-19T22:09:57.404Z
    description: add kanban | card toggle and kanban view for issues
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 4
  - id: tas-5nDpXesQ
    type: task
    title: Add Sprint Dropdown
    status: done
    createdAt: 2026-02-19T18:03:56.551Z
    updatedAt: 2026-02-19T18:23:21.011Z
    description: >-
      Create sprint filter for ticket dashboard, allowing [no sprint] to show tickets without a sprint, or [all tickets]
      to show everything.


      The top numbers (total tickets, bugs, in progress, done) should update to reflect how many are in that sprint.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 2
  - id: tas-6-1ZdYM2
    type: task
    title: A11y pass
    status: todo
    createdAt: 2026-02-19T20:58:08.972Z
    updatedAt: 2026-02-19T20:58:08.972Z
    description: Update web ui for accessibility standards
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 2
  - id: tas-6Hvm9w-9
    type: task
    title: Fix NPM vulnerabilities
    status: done
    createdAt: 2026-02-19T18:05:01.380Z
    updatedAt: 2026-02-19T18:41:30.578Z
    description: There were several critical vulnerabilities. These should be fixed before go-live.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: critical
    estimate: 3
  - id: tas-ArT7lw8y
    type: task
    title: Publish to NPM
    status: todo
    createdAt: 2026-02-19T18:52:30.049Z
    updatedAt: 2026-02-19T19:44:53.901Z
    description: >-
      Publishing to npm involves preparing your package, logging in, and using the npm publish command.  Ensure your
      project has a valid package.json with required fields like name, version, description, and main. Use npm init to
      generate or update it. 


      For public packages:

      Create an account at npmjs.com.

      Log in via CLI: npm login.

      Publish with: npm publish.

      For scoped packages (e.g., @username/package), use npm publish --access public on first publish. 

      For private packages:

      Requires a paid npm account.

      Scoped packages are private by default.

      Use npm publish (ensure 2FA or a granular access token is set up). 

      Build and test:

      Use prepublish or prepublishOnly scripts to build (e.g., npm run build) before publishing.

      Set main to the built file (e.g., dist/index.js).

      Use files in package.json to include only necessary files.

      Test locally with npm link and npm install. 

      Versioning:

      Use semantic versioning (semver). 

      Increment versions with:

      npm version patch (1.0.0 → 1.0.1)

      npm version minor (1.0.0 → 1.1.0)

      npm version major (1.0.0 → 2.0.0) 

      Automate with GitHub Actions:

      Use workflows triggered on release to publish automatically. Include --provenance for supply chain security and
      --access public for public packages. 

      Common issues:

      Package name taken? Choose a unique name or scope. 

      Version already exists? Increment the version. 

      Publish denied? Ensure login and permissions are correct. 

      Cannot read properties of undefined? Avoid npm access grant for new packages; use --access public instead. 

      Always include a README.md, tests, and a CHANGELOG.md for maintainability.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: low
    estimate: 5
  - id: tas-CQAh7pz-
    type: task
    title: Persist web ui settings
    status: done
    createdAt: 2026-02-19T22:08:58.682Z
    updatedAt: 2026-02-19T22:56:20.078Z
    description: |-
      Last selected web ui options should be persisted locally (gitignored) 
      - dark mode
      - View mode
      - Filter by sprint
      - Last Filters
      - Last Search Term
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 3
  - id: tas-Ds4qx-En
    type: task
    title: Add Functionality to Ticket Summary Elements
    status: done
    createdAt: 2026-02-19T18:40:30.671Z
    updatedAt: 2026-02-19T21:11:47.195Z
    description: >-
      The big counts on the top of the screen: Total Tickets, Bugs, In Progress, Completed, should be clickable and take
      the user to the respective view for what they clicked on. Eg. Click Bugs => User is on Bugs view


      Clicking on the entire element should perform the function, not just the icon or text.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 1
  - id: tas-dZLxtPlg
    type: task
    title: Expand large tickets
    status: done
    createdAt: 2026-02-19T19:45:28.931Z
    updatedAt: 2026-02-19T20:11:02.575Z
    description: For tickets with long descriptions, allow expanding to view the entire ticket.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: high
    estimate: 2
  - id: tas-fhgLnI-R
    type: task
    title: Controls Hamburger UI
    status: done
    createdAt: 2026-02-19T21:02:34.677Z
    updatedAt: 2026-02-19T22:40:04.209Z
    description: |-
      Put search, filter, manage, light/dark into hamburger UI
      Move new ticket button to floating location
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 2
  - id: tas-hhWcu34a
    type: task
    title: Add Conversations
    status: done
    createdAt: 2026-02-19T18:07:17.047Z
    updatedAt: 2026-02-19T20:48:11.074Z
    description: >-
      As progress on tickets is made, users may want to add comments to the ticket. Add a conversion feature to keep
      running messages with a modal to display and add more comments.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: low
    estimate: 3
  - id: tas-irmznurf
    type: task
    title: Dark mode
    status: done
    createdAt: 2026-02-19T19:41:41.299Z
    updatedAt: 2026-02-19T19:59:02.343Z
    description: Add dark mode to web ui
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: critical
    estimate: 2
  - id: tas-IvIExFTv
    type: task
    title: Add CLI support for comments
    status: done
    createdAt: 2026-02-19T20:54:43.764Z
    updatedAt: 2026-02-19T21:45:05.645Z
    description: Add CLI commands to get and create comments, add them to mcp
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 1
  - id: tas-kAr0SMMg
    type: task
    title: Clean up and align UI
    status: done
    createdAt: 2026-02-19T20:28:00.628Z
    updatedAt: 2026-02-19T22:39:58.759Z
    description: >-
      Add padding above progress bar

      align search, filter, and ticket and manage buttons (currently labeled inputs lower than the buttons and it looks
      off.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 2
  - id: tas-kaW_Dd9v
    type: task
    title: Remove file bloat from expired bugs/tasks
    status: done
    createdAt: 2026-02-19T21:00:32.700Z
    updatedAt: 2026-02-20T00:25:19.460Z
    description: >-
      When a sprint is closed, flatten the related bugs, tasks, and related comments into one doc (probably the sprint
      doc)
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 3
  - id: tas-KIMP1Fog
    type: task
    title: Add Versioning
    status: done
    createdAt: 2026-02-19T18:39:15.617Z
    updatedAt: 2026-02-19T21:19:56.506Z
    description: Implement versioning to tkxr starting at 1.0.0 for this release
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 1
  - id: tas-KzHFhmtx
    type: task
    title: Sprint Progress Bar
    status: done
    createdAt: 2026-02-19T19:24:55.507Z
    updatedAt: 2026-02-19T20:26:22.823Z
    description: >-
      When this is a sprint selected in the dashboard, show a progress bar (with percentage) that fills based on how
      many points are done/remaining in the sprint.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 3
  - id: tas-P1GRoZp8
    type: task
    title: Add Ticket Searching and Sorting
    status: done
    createdAt: 2026-02-19T18:31:57.128Z
    updatedAt: 2026-02-19T18:50:42.057Z
    description: Allow tickets to be searched or ordered based on user criteria. Pop open a form to do searches and filters.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 3
  - id: tas-P1UxtjbC
    type: task
    title: Split categories
    status: done
    createdAt: 2026-02-19T18:30:41.824Z
    updatedAt: 2026-02-19T19:27:18.528Z
    description: |-
      Instead of current ticket view categories: All tickets, tasks, bugs, to do, in progress, done

      Separate filters into All Tickets, Open Tasks, Open Bugs, To Do, In Progress, Done
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 1
  - id: tas-p7P0gOjE
    type: task
    title: 'Feature: MCP Server'
    status: done
    createdAt: 2026-02-19T18:02:38.689Z
    updatedAt: 2026-02-19T18:18:42.481Z
    description: Add mcp for ai to use the cli and manage tickets.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 2
  - id: tas-PO11dk8L
    type: task
    title: '"My" user'
    status: done
    createdAt: 2026-02-19T20:19:57.083Z
    updatedAt: 2026-02-19T22:59:59.948Z
    description: >-
      Allow selection of current user from a dropdown. Default assign this user when creating new tickets as assignee or
      posting comments
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 2
  - id: tas-QEtr9PCO
    type: task
    title: Rename default ticket dir
    status: done
    createdAt: 2026-02-19T18:15:03.744Z
    updatedAt: 2026-02-19T21:15:39.386Z
    description: Instead of /tickets/ use a default dir name of /tkxr/ to avoid collisions with other systems.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: low
    estimate: 1
  - id: tas-rMM9imow
    type: task
    title: Misleading sprint complete button
    status: done
    createdAt: 2026-02-19T19:40:35.940Z
    updatedAt: 2026-02-19T20:20:16.519Z
    description: >-
      The green "Complete" button on the sprint UI looks too much like a tag that shows a complete status. Make it look
      more like a button and not a tag.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 1
  - id: tas-uK1EDig1
    type: task
    title: Better Naming on Tickets
    status: done
    createdAt: 2026-02-19T18:00:27.660Z
    updatedAt: 2026-02-19T19:38:28.455Z
    description: Task/Bug shows user id, sprint id, not name. Have these display name instead.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: low
    estimate: 1
  - id: tas-YWmnoecK
    type: task
    title: CLI does not publish updates to UI
    status: done
    createdAt: 2026-02-19T18:24:13.205Z
    updatedAt: 2026-02-19T19:21:16.466Z
    description: When the CLI is used, the status and tickets shown in the web UI do not update. Perhaps some polling is needed?
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: low
    estimate: 2
  - id: bug-LeFQk1aa
    type: bug
    title: Modals don't support dark mode
    status: done
    createdAt: 2026-02-19T20:14:22.332Z
    updatedAt: 2026-02-19T21:04:23.936Z
    description: >-
      Both ticket and manage modals do not have a dark mode, but their text is affected by it, leading to them being
      unusable in dark mode.
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: critical
    estimate: 2
  - id: bug-oR_m-Udg
    type: bug
    title: Horizonal scroll in kanban
    status: done
    createdAt: 2026-02-19T22:41:57.600Z
    updatedAt: 2026-02-19T22:45:28.339Z
    description: >-
      When hovering ticket card elements, they grow a bit, which causes a horizonal scroll to appear on the kanban lane.
      We don't want that to happen
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 2
  - id: bug-Tg-5H4lg
    type: bug
    title: Deleting ticket leaves orphan comments
    status: done
    createdAt: 2026-02-19T23:03:42.672Z
    updatedAt: 2026-02-19T23:05:49.447Z
    description: We need to delete related comments when deleting a ticket
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: medium
    estimate: 2
  - id: bug-tldIhhfZ
    type: bug
    title: Search/filter order issue
    status: done
    createdAt: 2026-02-19T18:53:40.235Z
    updatedAt: 2026-02-19T19:10:25.069Z
    description: |-
      Priority sort is not sorting priority correctly. It should filter all tasks/bugs in the order:
      critical bug, critical task, high bug, high task, med bug, med task, low bug, low task
    assignee: use-JTYCH2se
    sprint: spr-hDifgOv0
    priority: high
  - id: tas-8xUIxtgy
    type: task
    title: Test single-file storage
    status: todo
    createdAt: 2026-02-20T00:10:02.458Z
    updatedAt: 2026-02-20T00:10:02.458Z
sprints:
  - id: spr-GqmnrDyV
    name: JIRA Integration
    status: planning
    createdAt: 2026-02-19T20:16:49.208Z
    updatedAt: 2026-02-19T20:16:49.208Z
    description: Integration with JIRA Platform
    goal: 'Pull down/Push up with JIRA '
  - id: spr-hDifgOv0
    name: tkxr MVP Development
    status: active
    createdAt: 2026-02-19T17:33:57.888Z
    updatedAt: 2026-02-19T18:24:27.649Z
    description: Implement all features, fix all bugs, etc.
    goal: Release tkxr!
  - id: spr-F_JWOvN-
    name: Test Sprint
    status: completed
    createdAt: 2026-02-20T00:15:23.940Z
    updatedAt: 2026-02-20T00:16:59.614Z
    description: Sprint for testing archiving functionality
    goal: Test the sprint archiving feature
users:
  - id: use-3NNxU7_G
    username: User 2
    displayName: SecondUser
    createdAt: 2026-02-19T20:36:10.948Z
    updatedAt: 2026-02-19T20:36:10.948Z
    email: UserTwo@jacks.com
  - id: use-JTYCH2se
    username: Andrew
    displayName: AndrewAtJacks
    createdAt: 2026-02-19T17:23:45.272Z
    updatedAt: 2026-02-19T17:23:45.272Z
    email: andrew@jacks.com
comments:
  - id: com-76hK6vvE
    ticketId: tas-IvIExFTv
    author: use-JTYCH2se
    content: '✅ TASK COMPLETED! '
    createdAt: 2026-02-19T21:46:08.089Z
    updatedAt: 2026-02-19T21:46:08.089Z
  - id: com-9QJRm_W4
    ticketId: tas-hhWcu34a
    author: use-JTYCH2se
    content: Looks like the comments work correctly, good!
    createdAt: 2026-02-19T20:43:58.325Z
    updatedAt: 2026-02-19T20:43:58.325Z
  - id: com-Ej_OPBkI
    ticketId: tas-IvIExFTv
    author: use-JTYCH2se
    content: >-
      🤖 SUCCESS! This comment was added by an AI assistant using the MCP server we just built! The integration is
      working perfectly!
    createdAt: 2026-02-19T21:43:46.470Z
    updatedAt: 2026-02-19T21:43:46.470Z
  - id: com-iRr2Nk8-
    ticketId: tas-PO11dk8L
    author: use-JTYCH2se
    content: Let's throw this into the hamburger menu, with a default of "no user"
    createdAt: 2026-02-19T22:57:01.097Z
    updatedAt: 2026-02-19T22:57:01.097Z
  - id: com-Lo9XfaQg
    ticketId: tas-hhWcu34a
    author: use-3NNxU7_G
    content: They should be in chronological order now, too.
    createdAt: 2026-02-19T20:46:53.137Z
    updatedAt: 2026-02-19T20:46:53.137Z
  - id: com-LPSDndxD
    ticketId: tas-hhWcu34a
    author: use-JTYCH2se
    content: Test Comment
    createdAt: 2026-02-19T20:35:46.334Z
    updatedAt: 2026-02-19T20:35:46.334Z
  - id: com-t3WlIXPZ
    ticketId: tas-IvIExFTv
    author: use-JTYCH2se
    content: CLI comments functionality has been implemented and is working correctly!
    createdAt: 2026-02-19T21:29:01.610Z
    updatedAt: 2026-02-19T21:29:01.610Z
  - id: com-WQOHdwCP
    ticketId: tas-kaW_Dd9v
    author: use-JTYCH2se
    content: >-
      Made a bit of a design decision here. Going forward, active work is stored in a main project.yaml file
      (tkxr/project.yaml) and archived (closed) sprints get removed from this file to their own archive files 
      (tkxr/archives/archive_abc123.yaml)
    createdAt: 2026-02-20T00:24:55.874Z
    updatedAt: 2026-02-20T00:24:55.874Z
